# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ItFriendly group Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Run-on-Chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Maven test
      run: mvn test
      env:
        ENV_BROWSER_NAME: "CHROME"

    - name: Attach screenshots and reports Chrome
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-and-report-Chrome
        path: |
          screenshots
          target/surefire-reports/emailable-report.html

  Good-Job:
    runs-on: ubuntu-latest
    needs: Bad-Luck
    if: skip()
    steps:
      - run: echo "WOW !!!!!!  "

  Bad-Luck:
    runs-on: ubuntu-latest
    needs: Run-on-Chrome
    if: failure()
    steps:
        - run: echo "FAIL !!!! "

  Run-on-FireFox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Maven test
        run: mvn test
        env:
          ENV_BROWSER_NAME: "FIREFOX"

